### ISSUE TITLE
Console errors on loading Foundry

### ISSUE THREAD

**Issue by weepingminotaur** [jsavko/boss-splash#10]
Getting this console error, which seems to involve Boss Splash Screen, every time I load my Foundry world. Have reproduced with 0 modules active except BSS, libwrapper, and socketlib. Foundry v11 build 315, Pathfinder 2e 5.15.
<img width="585" alt="Screenshot 2024-04-16 at 4 28 40 PM" src="https://github.com/jsavko/boss-splash/assets/90105219/034b5b65-f051-4e26-99dc-8d51ee2c2a64">

**Comment by jsavko** [comment]
Looks like this is a product of adding font selection in and the setting not being loaded in time for the context menu rendering.  I've resolved the issue by moving all the settings back to init and populating the fonts to `renderSettingsConfig` and will be fixed in 1.1.6 which I am building for release right now
